---
version: "3"

tasks:
  format:
    cmds:
      - fd '.nix' | xargs nixfmt

  update:
    cmds:
      - nix flake update

  nh:
    cmds:
      - nh os switch .

  switch:
    cmds:
      - sudo nixos-rebuild switch --flake .

  update-switch:
    cmds:
      - task: update
      - task: nh

  switch-next-boot:
    cmds:
      - sudo nixos-rebuild boot --flake .

  build:
    cmds:
      - sudo nixos-rebuild build --flake .

  clean-garbage:
    cmds:
      - nix-collect-garbage

  clean-generations:
    cmds:
      - nh clean user -k 3

  clean:
    cmds:
      - task: clean-garbage
      - task: clean-generations
